[package]
name = "kaktus"
version = "0.1.1"
authors = ["Jasper Schulz <jasper.b.schulz@gmail.com>"]
description = "Parent Pointer Tree"
repository = "https://github.com/softdevteam/kaktus"
license = "MIT/Apache-2.0"

[dependencies]
